### PR TITLE
Implement bookshelf feature #12

### PR DESCRIPTION
**Pull request by KazukiSenda**
At first, books page is done!

### CODE REVIEW

**Comment by WEI44ZHEYUAN** [comment]
We dont need the template, We just need backend part, frontend is in charge by TAKAYAMA and atsuhito san, and please use anorther API name for add book , I already use register for authentication system.

**Comment by WEI44ZHEYUAN** [comment]
And Please use the database that TAKAYAMA san already Post on the github

**Comment by MGMCN** [comment]
How to run your porj ? Me and yuan cant run your proj corectly. (Error occurs)

**Comment by WEI44ZHEYUAN** [comment]
KazukiSenda san can you push your runable code to the github, I will try to fix the docker problem for you

**Pull request merged**
